### ISSUE TITLE
Dubious evaluation when running out of gates

### ISSUE THREAD

**Issue by ceebo** [ianfab/Seirawan-Stockfish#11]
In position `8/4pppp/q7/k7/8/8/5PPP/5NK1[E] b F - 0 1` black has the winning move Qxf1 sacrificing queen for knight, leaving white with a stranded elephant and ending up in a winning king and pawn endgame. I guess that all other moves should be losing because white can gate an elephant on the next turn.

Current master with Lazy Evaluation doesn't find the move Qxf1:

```
position fen 8/4pppp/q7/k7/8/8/5PPP/5NK1[E] b F - 0 1
go depth 20
info depth 20 seldepth 33 multipv 1 score cp -208 nodes 1917858 nps 372689 hashfull 659 tbhits 0 time 5146 pv a5b4 f1d2e a6f1 g1f1 f7f6 f1e2 b4c5 e2e3 c5d5 f2f4 g7g5 f4g5 f6g5 d2e4 h7h6 g2g4 d5e5 e4g3 e5f6 e3e4 f6f7 g3f5
```

No problem, we can get rid of Lazy Eval.... Now the move is found instantly but the evaluation is still in white's favour. Strange!

```
position fen 8/4pppp/q7/k7/8/8/5PPP/5NK1[E] b F - 0 1
go depth 20
info depth 20 seldepth 28 multipv 1 score cp -63 nodes 1417102 nps 470173 hashfull 427 tbhits 0 time 3014 pv a6f1 g1f1 a5b5 f1e2 b5c5 e2e3 c5d5 e3f4 f7f6 f4e3 g7g5 h2h4 g5h4 e3f4 d5d4 f4g4 d4d3 g4h4 d3e2 h4g3 e7e5 f2f3 e2e3 g3g4 e3f2
```

The reason is that after Qxf1 Kxf1 the white elephant is scored as an endgame piece but only penalised as a middlegame piece (also the addition of 50 in psqt.cpp contributes slightly):

```
position fen 8/4pppp/q7/k7/8/8/5PPP/5NK1[E] b F - 0 1 moves a6f1 g1f1
eval
      Eval term |    White    |    Black    |    Total    
                |   MG    EG  |   MG    EG  |   MG    EG  
----------------+-------------+-------------+-------------
       Material |   ---   --- |   ---   --- |  8.30  9.52 
      Imbalance |   ---   --- |   ---   --- |  0.00  0.00 
          Pawns |   ---   --- |   ---   --- | -0.07  0.02 
        Knights |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
        Bishops |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
          Rooks |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
          Hawks |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
      Elephants |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
         Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
       Mobility |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
    King safety |  0.63 -0.07 | -0.32 -0.59 |  0.95  0.52 
        Threats | -8.41 -8.41 |  0.00  0.00 | -8.41 -8.41 
   Passed pawns |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
          Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
     Initiative |   ---   --- |   ---   --- |  0.00 -0.15 
----------------+-------------+-------------+-------------
          Total |   ---   --- |   ---   --- |  0.77  1.50 

Total Evaluation: 1.42 (white side)
```

Always scoring hand pieces in psqt and then removing them from the score if they turn out to be unplayable seems error-prone. One option is to remove all pieces from the hand if there are no gating squares. I'm not sure I like this for a couple of reasons:

1. Hand pieces are counted in Position, so we would need to restore hand pieces in undo_move when gatesBB goes from empty to non-empty. GatesBB can change with any kind of move so this test would add overhead to all types of move, not just gating moves. Also (I think) we would need some way of remembering which hand pieces we had before. I don't think there is a way to do this at the moment.

2. It doesn't address the issue of sacrificing a piece to remove a gating square of the opponent and leaving him with one gating square left but having two pieces in hand.

So dealing with this in evaluation looks better to me. I have in mind some code that takes hand pieces out of the PSQT scoring and evaluate the hand as a bonus instead of as a penalty. More to follow on this later...

**Comment by ianfab** [comment]
@ceebo Thanks for the analysis. I think a consistent evaluation of pieces in hand is important and might give a big gain in playing strength.

I also think that it would be problematic to remove pieces in hand when no gates are left. When I implemented S-Chess, I had my crazyhouse implementation in mind and did not consider that one might require a different approach for the PSQT handling of pieces in hand due to the fact that dropping/gating is not unconditional as in crazyhouse. I now agree that it makes sense to remove the pieces in hand from PSQT handling and instead add a bonus (depending on the number of remaining gates) in the evaluation. For crazyhouse that would not make much sense, but here it does, since we then do not have to fine-tune the penalty to cancel out the PSQT value.

**Comment by ceebo** [comment]
@ianfab Just now I pushed some commits and hopefully started a sensible tuning run.

The main part of the commit is here https://github.com/ceebo/Seirawan-Stockfish/commit/f7010e1d46ec3a7c73174ad8f9d38a219a92ca26

Things I like about the implementation is that

1. The behviour of the engine is nearly identical when one side has an unplayable hand piece compared to when that piece is not in the hand at all. I hope that the only difference is because of the different Zobrist keys and the effect of that on the hash table.

2. The scoring of absolutely unplayable hand pieces is separate from the "Gate mobility" aspect of the evaluation.

3. It's almost a no-op in the case of an empty hand so I hope it is fast.

Anyway, that's all just words. I hope it can at least be as strong as the old way...

**Comment by ianfab** [comment]
@ceebo Looks good to me. I would be ok with testing such a refactoring with [-10,5] bounds, because it makes it easier to improve the evaluation of pieces in hand, so it does not necessarily have to be an improvement itself.

**Comment by ceebo** [comment]
@ianfab The tuning run looked sensible and a quick local test gave ELO +100 +/-60 in a 100 game match. I just started up a couple standard tests on fishtest.

**Comment by ianfab** [comment]
That sounds promising. This order of magnitude in Elo gain might well be possible for such an important evaluation term.

**Comment by ianfab** [comment]
STC and LTC seem to confirm (or even exceed) the +100 Elo estimate, congrats. If you create a PR, please from now on include the bench number in the commit message (something like `bench: 1234567`, just like for official stockfish), since I enabled Travis CI.

**Comment by ceebo** [comment]
Thanks, a very pleasing result. The new bonus increases when going from 2->1 pieces in hand and then goes down to 0 when going from 1->0 pieces in hand. I never would have guessed this without the auto-tuner. I will probably make a PR a bit later since I suppose I should add a new tracing term for completeness.
